# MythicMobs Configuration - Ghost/Phantom Mob
# Mob Definitions
Ghost:
  Type: PHANTOM
  Display: '&f&lПризрак'
  Health: 40
  Damage: 8
  Armor: 2
  Options:
    MovementSpeed: 0.3
    FollowRange: 32
    Silent: false
    PreventOtherDrops: true
  AIGoalSelectors:
  - clear
  - meleeattack
  - randomstroll
  AITargetSelectors:
  - clear
  - attacker
  - players
  Equipment:
  - AIR:4
  - AIR:3
  - AIR:2
  - AIR:1
  - AIR:0
  Drops:
  - PHANTOM_MEMBRANE 1-2 0.5
  Skills:
  - effect:blindness{duration=60} @target ~onAttack 0.3
  - particlebox{particle=soul;amount=20;speed=0.1} @self ~onTimer:100
# Chronomancer - Time Mage Mob
Chronomancer:
  Type: EVOKER
  Display: '&b&lХрономант'
  Health: 120
  Damage: 15
  Armor: 6
  Options:
    MovementSpeed: 0.25
    FollowRange: 48
    Silent: false
    PreventOtherDrops: true
    KnockbackResistance: 0.5
  AIGoalSelectors:
  - clear
  - meleeattack
  - randomstroll
  - lookatplayers
  AITargetSelectors:
  - clear
  - attacker
  - players
  Equipment:
  - DIAMOND_HELMET:4
  - DIAMOND_CHESTPLATE:3
  - DIAMOND_LEGGINGS:2
  - DIAMOND_BOOTS:1
  - CLOCK:0
  Drops:
  - CLOCK 1 0.8
  - DIAMOND 2-4 0.4
  - EXPERIENCE_BOTTLE 3-5 0.6
  - ENCHANTED_BOOK 1 0.2
  Skills:
  # Skill 1: Time Rewind - Heals self and negates recent damage
  - heal{amount=30} @self ~onDamaged 0.25
  - effect:regeneration{duration=100;amplifier=2} @self ~onDamaged 0.25
  - particleline{particle=end_rod;amount=50;zigzag=true} @self ~onDamaged 0.25
  - sound{sound=entity.enderman.teleport;volume=1.5} @self ~onDamaged 0.25
  # Skill 2: Time Freeze - Visual and sound effects only
  - particlesphere{particle=witch;amount=100;radius=10} @self ~onTimer:200 1.0
  - sound{sound=block.beacon.activate;volume=2.0} @self ~onTimer:200 1.0
  # Skill 3: Temporal Acceleration - Speeds up self and nearby allies
  - effect:speed{duration=200;amplifier=3} @self ~onTimer:300 1.0
  - effect:haste{duration=200;amplifier=2} @self ~onTimer:300 1.0
  - effect:regeneration{duration=200;amplifier=1} @self ~onTimer:300 1.0
  - effect:speed{duration=200;amplifier=2} @MobsInRadius{r=15;types=EVOKER,VINDICATOR,ZOMBIE,SKELETON} ~onTimer:300 1.0
  - particleline{particle=portal;amount=30;fromorigin=true} @self ~onTimer:300 1.0
  - sound{sound=entity.illusioner.mirror_move;volume=1.5} @self ~onTimer:300 1.0
  # Additional combat effects
  - particlebox{particle=dragon_breath;amount=15;speed=0.05} @self ~onTimer:60
# Spawn Configurations
Spawns:
  Ghost_Spawn:
    Mob: Ghost
    World: world
    Biomes:
    - PLAINS
    - FOREST
    - DARK_FOREST
    Chance: 0.05
    Priority: 1
    Conditions:
    - night
    - playerwithin{distance=64}
  
  Chronomancer_Spawn:
    Mob: Chronomancer
    World: world
    Biomes:
    - MOUNTAINS
    - TAIGA
    - SNOWY_TUNDRA
    - END_HIGHLANDS
    Chance: 0.02
    Priority: 5
    Conditions:
    - night
    - playerwithin{distance=80}
    - height{min=80}
